"""tabels

Revision ID: 073161de7278
Revises: 
Create Date: 2026-06-29 18:46:22.574288

"""
from typing import Sequence, Union
import sqlalchemy_file
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073161de7278'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parasha',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('image', sqlalchemy_file.types.ImageField(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_type',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('person',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('family_name', sa.String(length=512), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_rabbie', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('image', sqlalchemy_file.types.ImageField(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_account',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_title', sa.String(length=512), nullable=False),
    sa.Column('sheba_number', sa.String(length=26), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('payment_type_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['payment_type_id'], ['payment_type.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_model',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('is_answered', sa.Boolean(), server_default='False', nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('rabbie_id', sa.String(length=36), nullable=True),
    sa.Column('talmid_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['rabbie_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['talmid_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('verification_code', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('payment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('authority', sa.String(length=255), nullable=True),
    sa.Column('ref_id', sa.String(length=255), nullable=True),
    sa.Column('card_pan', sa.String(length=25), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'CANCELLED', 'EXPIRED', name='paymentstatusenum'), nullable=False),
    sa.Column('payment_account_id', sa.String(length=36), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['payment_account_id'], ['payment_account.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('user')
    op.drop_table('qa_model')
    op.drop_table('payment_account')
    op.drop_table('person')
    op.drop_table('payment_type')
    op.drop_table('parasha')
    # ### end Alembic commands ###
