"""is rabbie not null

Revision ID: 8271df8b68ec
Revises: e8297eb8491f
Create Date: 2026-06-05 14:22:22.550700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8271df8b68ec'
down_revision: Union[str, Sequence[str], None] = 'e8297eb8491f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'is_rabbie',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'is_rabbie',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
