"""add user table with personid foreign key

Revision ID: e8297eb8491f
Revises: faa480ef6d69
Create Date: 2026-05-30 15:54:30.079876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8297eb8491f'
down_revision: Union[str, Sequence[str], None] = 'faa480ef6d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('verification_code', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('person', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('person', sa.Column('family_name', sa.String(length=512), nullable=True))
    op.add_column('person', sa.Column('is_rabbie', sa.Boolean(), nullable=True))
    op.add_column('person', sa.Column('image_path', sa.String(length=255), nullable=True))
    op.drop_column('person', 'phone')
    op.drop_column('person', 'email')
    op.drop_column('person', 'verification_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('verification_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('person', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('person', sa.Column('phone', sa.VARCHAR(length=11), autoincrement=False, nullable=False))
    op.drop_column('person', 'image_path')
    op.drop_column('person', 'is_rabbie')
    op.drop_column('person', 'family_name')
    op.drop_column('person', 'name')
    op.drop_table('user')
    # ### end Alembic commands ###
