"""add parasha table

Revision ID: faa480ef6d69
Revises: d722aa9375da
Create Date: 2026-05-27 16:28:50.559969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faa480ef6d69'
down_revision: Union[str, Sequence[str], None] = 'd722aa9375da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parasha',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('person', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('person', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('person', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('person', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('person', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('person', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('person', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('parasha')
    # ### end Alembic commands ###
