services:
  db_talmood26:
    image: postgres:latest
    container_name: db_talmood26
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"

  redis_talmood26:
    image: redis:7-alpine
    container_name: redis_talmood26
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    # اگر بخوای persistence داشته باشی، می‌تونی این رو هم اضافه کنی:
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--save", "20", "1", "--loglevel", "warning"]

  backend_talmood26:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_talmood26
    restart: always
    depends_on:
      - db_talmood26
      - redis_talmood26
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db_talmood26:5432/postgres
      JWT_SECRET_KEY: Testkjfejdfqwejd;qwekd;qwkd;qwekd;qwkd;qwkdjfjwefj
      REDIS_URL: redis://redis:6379
      UPLOAD_DIR: /usr/src/core/static/parasha_images
      UPLOAD_URL_PREFIX: /static/parasha_images
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    volumes:
      - ./app:/usr/src/core
      - ./static:/usr/src/core/static

# docker-compose up --build -d
# docker exec -it backend_talmood26 bash (For running commands in docker terminal)
# docker-compose exec backend_talmood26 alembic revision --autogenerate -m "add person table"
# docker-compose exec backend_talmood26 alembic upgrade head
# docker-compose up -d db_talmood26 redis_talmood26