services:

  db-talmood26:
    image: postgres:17
    container_name: db-talmood26
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    ports:
      - "5432:5432"


  redis-talmood26:
    image: redis:7-alpine
    container_name: redis-talmood26
    restart: always

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s


  backend-talmood26:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: backend-talmood26
    restart: always

    depends_on:
      db-talmood26:
        condition: service_healthy

      redis-talmood26:
        condition: service_healthy

    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://root:kiPeDubirwYmYahDrynrsl7u@siah-kaman.liara.cloud:34923/postgres
      # SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db-talmood26:5432/postgres

      JWT_SECRET_KEY: "Testkjfejdfqwejd;qwekd;qwkd;qwekd;qwkd;qwkdjfjwefj"

      REDIS_URL: redis://redis-talmood26:6379

      UPLOAD_DIR: /usr/src/core/static/parasha_images

      UPLOAD_URL_PREFIX: /static/parasha_images

    ports:
      - "8000:8000"

volumes:
  postgres-data: